services:
  api:
    image: aparup2004/urlshortner
    container_name: urlShortner-app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: urlShortner-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: urlShortner
    volumes:
      - "/urlDb:/var/lib/postgresql"

